/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import model.Produto;
import modelo.dao.ProdutoDAO;

/**
 *
 * @author Fujoshi Shouter
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        espacoPn = new javax.swing.JScrollPane();
        mensagemLbl = new javax.swing.JLabel();
        tituloLbl = new javax.swing.JLabel();
        dadosPn = new javax.swing.JPanel();
        precoLbl = new javax.swing.JLabel();
        descricaoLbl = new javax.swing.JLabel();
        nomeLbl = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        transportadoraLbl = new javax.swing.JLabel();
        origemLbl = new javax.swing.JLabel();
        codigoLbl = new javax.swing.JLabel();
        materialLbl = new javax.swing.JLabel();
        proprietarioLbl = new javax.swing.JLabel();
        contatoLbl = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        nomeTxt = new javax.swing.JTextField();
        descricaoTxt = new javax.swing.JTextField();
        precoTxt = new javax.swing.JTextField();
        transportadoraTxt = new javax.swing.JTextField();
        origemTxt = new javax.swing.JTextField();
        codigoTxt = new javax.swing.JTextField();
        materialTxt = new javax.swing.JTextField();
        proprietarioTxt = new javax.swing.JTextField();
        contatoTxt = new javax.swing.JTextField();
        botoesPn = new javax.swing.JPanel();
        cadastrarBtn = new javax.swing.JButton();
        atualizarBtn = new javax.swing.JButton();
        consultarbyidBtn = new javax.swing.JButton();
        consultartodosBtn = new javax.swing.JButton();
        deletarBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        opcaoJM = new javax.swing.JMenu();
        cadastrarJMI = new javax.swing.JMenuItem();
        atualizarJMI = new javax.swing.JMenuItem();
        consultabyidJMI = new javax.swing.JMenuItem();
        consultatodosJMI = new javax.swing.JMenuItem();
        deletarFMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        espacoPn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mensagemLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mensagemLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        espacoPn.setViewportView(mensagemLbl);

        tituloLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloLbl.setText("INSIRA OS DADOS ABAIXO");

        dadosPn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        precoLbl.setText("Preço:");

        descricaoLbl.setText("Descrição:");

        nomeLbl.setText("Nome do produto:");

        idLbl.setText("ID:");

        transportadoraLbl.setText("Transportadora:");

        origemLbl.setText("Origem:");

        codigoLbl.setText("Código:");

        materialLbl.setText("Material:");

        proprietarioLbl.setText("Proprietário:");

        contatoLbl.setText("Contato:");

        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });

        nomeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTxtActionPerformed(evt);
            }
        });

        precoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoTxtActionPerformed(evt);
            }
        });

        proprietarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proprietarioTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dadosPnLayout = new javax.swing.GroupLayout(dadosPn);
        dadosPn.setLayout(dadosPnLayout);
        dadosPnLayout.setHorizontalGroup(
            dadosPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosPnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(dadosPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosPnLayout.createSequentialGroup()
                        .addComponent(nomeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosPnLayout.createSequentialGroup()
                        .addComponent(transportadoraLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(transportadoraTxt))
                    .addGroup(dadosPnLayout.createSequentialGroup()
                        .addComponent(contatoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contatoTxt))
                    .addGroup(dadosPnLayout.createSequentialGroup()
                        .addComponent(idLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(precoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(precoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosPnLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(origemLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(origemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(codigoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosPnLayout.createSequentialGroup()
                        .addComponent(descricaoLbl)
                        .addGap(18, 18, 18)
                        .addComponent(descricaoTxt))
                    .addGroup(dadosPnLayout.createSequentialGroup()
                        .addComponent(materialLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(materialTxt))
                    .addGroup(dadosPnLayout.createSequentialGroup()
                        .addComponent(proprietarioLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(proprietarioTxt)))
                .addGap(18, 18, 18))
        );
        dadosPnLayout.setVerticalGroup(
            dadosPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosPnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(dadosPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLbl)
                    .addComponent(precoLbl)
                    .addComponent(precoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLbl)
                    .addComponent(nomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricaoLbl))
                .addGap(18, 18, 18)
                .addGroup(dadosPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportadoraLbl)
                    .addComponent(transportadoraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origemLbl)
                    .addComponent(codigoLbl)
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dadosPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialLbl))
                .addGap(18, 18, 18)
                .addGroup(dadosPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proprietarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proprietarioLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contatoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contatoLbl))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        cadastrarBtn.setText("CADASTRAR");
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        atualizarBtn.setText("ATUALIZAR");
        atualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBtnActionPerformed(evt);
            }
        });

        consultarbyidBtn.setText("CONSULTAR BY ID");
        consultarbyidBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarbyidBtnActionPerformed(evt);
            }
        });

        consultartodosBtn.setText("CONSULTAR TODOS");
        consultartodosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultartodosBtnActionPerformed(evt);
            }
        });

        deletarBtn.setBackground(new java.awt.Color(255, 51, 51));
        deletarBtn.setText("DELETAR");
        deletarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botoesPnLayout = new javax.swing.GroupLayout(botoesPn);
        botoesPn.setLayout(botoesPnLayout);
        botoesPnLayout.setHorizontalGroup(
            botoesPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesPnLayout.createSequentialGroup()
                .addGroup(botoesPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(botoesPnLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cadastrarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atualizarBtn)
                        .addGap(12, 12, 12)
                        .addComponent(consultarbyidBtn))
                    .addGroup(botoesPnLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(consultartodosBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletarBtn)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        botoesPnLayout.setVerticalGroup(
            botoesPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesPnLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(botoesPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarbyidBtn)
                    .addComponent(atualizarBtn)
                    .addComponent(cadastrarBtn))
                .addGap(18, 18, 18)
                .addGroup(botoesPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deletarBtn)
                    .addComponent(consultartodosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        opcaoJM.setText("AJUDA");
        opcaoJM.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                opcaoJMMouseMoved(evt);
            }
        });
        opcaoJM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                opcaoJMMouseExited(evt);
            }
        });

        cadastrarJMI.setText("Cadastrar");
        cadastrarJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarJMIActionPerformed(evt);
            }
        });
        opcaoJM.add(cadastrarJMI);

        atualizarJMI.setText("Atualizar");
        atualizarJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarJMIActionPerformed(evt);
            }
        });
        opcaoJM.add(atualizarJMI);

        consultabyidJMI.setText("Consultar by ID");
        consultabyidJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultabyidJMIActionPerformed(evt);
            }
        });
        opcaoJM.add(consultabyidJMI);

        consultatodosJMI.setText("Consultar todos");
        consultatodosJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultatodosJMIActionPerformed(evt);
            }
        });
        opcaoJM.add(consultatodosJMI);

        deletarFMI.setText("Deletar");
        deletarFMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarFMIActionPerformed(evt);
            }
        });
        opcaoJM.add(deletarFMI);

        jMenuBar1.add(opcaoJM);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(espacoPn, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botoesPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dadosPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tituloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(espacoPn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tituloLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dadosPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(botoesPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarJMIActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Para realizar a atualização, consulte pelo ID do produto e apenas altere os dados que deseja modificar, EXCETO o ID, e clique no botão \"Atualizar\"!", "COMO ATUALIZAR?", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_atualizarJMIActionPerformed

    private void cadastrarJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarJMIActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Para realizar o cadastro, basta preencher todos os campos, EXCETO o ID, e clicar no botão \"Cadastrar\"!", "COMO CADASTRAR?", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cadastrarJMIActionPerformed

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void nomeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTxtActionPerformed

    private void proprietarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proprietarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proprietarioTxtActionPerformed

    private void atualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBtnActionPerformed
        // TODO add your handling code here:
        mensagemLbl.setText("...");
        ProdutoDAO pdao = new ProdutoDAO();
        Produto p = new Produto();
        p.setId((int) Double.parseDouble(idTxt.getText()));
        p.setNome(nomeTxt.getText());
        p.setDescricao(descricaoTxt.getText());
        p.setPreco(Double.parseDouble(precoTxt.getText()));
        p.setTransportadora(transportadoraTxt.getText());
        p.setOrigem(origemTxt.getText());
        p.setCodigo(codigoTxt.getText());
        p.setMaterial(materialTxt.getText());
        p.setProprietario(proprietarioTxt.getText());
        p.setContato(contatoTxt.getText());

        try {
            pdao.atualizar(p);
            mensagemLbl.setText("<html><strong>Atualizado com sucesso!</strong></html>");
            nomeTxt.setText("");
            descricaoTxt.setText("");
            precoTxt.setText("");
            transportadoraTxt.setText("");
            origemTxt.setText("");
            codigoTxt.setText("");
            materialTxt.setText("");
            proprietarioTxt.setText("");
            contatoTxt.setText("");
        } catch (ClassNotFoundException | SQLException ex) {
            mensagemLbl.setText("ERRO: " + ex.getMessage());
        }

    }//GEN-LAST:event_atualizarBtnActionPerformed

    private void deletarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarBtnActionPerformed
        // TODO add your handling code here:
        mensagemLbl.setText("...");
        ProdutoDAO pdao = new ProdutoDAO();
        Produto p = new Produto();
        p.setId(Integer.parseInt(idTxt.getText()));

        try {
            boolean idExiste = pdao.verificarExistenciaID(p);
            if (idExiste) {
                // Se o ID existe, exibir a caixa de diálogo de confirmação
                int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja deletar?", "Confirmação", JOptionPane.YES_NO_OPTION);

                if (confirmacao == JOptionPane.YES_OPTION) {
                    // Se o usuário confirmar, então tenta deletar
                    boolean deletado = pdao.deletar(p);
                    if (deletado) {
                        mensagemLbl.setText("<html><strong>Deletado com sucesso.</strong></html>");
                        idTxt.setText("");
                        nomeTxt.setText("");
                        descricaoTxt.setText("");
                        precoTxt.setText("");
                        transportadoraTxt.setText("");
                        origemTxt.setText("");
                        codigoTxt.setText("");
                        materialTxt.setText("");
                        proprietarioTxt.setText("");
                        contatoTxt.setText("");
                    }

                } else {
                    idTxt.setText("");
                    nomeTxt.setText("");
                    descricaoTxt.setText("");
                    precoTxt.setText("");
                    transportadoraTxt.setText("");
                    origemTxt.setText("");
                    codigoTxt.setText("");
                    materialTxt.setText("");
                    proprietarioTxt.setText("");
                    contatoTxt.setText("");
                    mensagemLbl.setText("");
                }
            } else {
                // Se o ID não existe, exibir mensagem de erro
                mensagemLbl.setText("<html><strong>Nenhum ID encontrado.</strong></html>");
                idTxt.setText("");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            mensagemLbl.setText("ERRO: " + ex.getMessage());
        }
    }//GEN-LAST:event_deletarBtnActionPerformed

    private void consultabyidJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultabyidJMIActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Para realizar a consulta por ID, basta preencher SOMENTE o campo ID, e clicar no botão \"Consulta by ID\"!", "COMO CONSULTAR POR ID", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_consultabyidJMIActionPerformed

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        // TODO add your handling code here:
        mensagemLbl.setText("...");
        idTxt.setText("");
        ProdutoDAO pdao = new ProdutoDAO();
        Produto p = new Produto();
        p.setNome(nomeTxt.getText());
        p.setDescricao(descricaoTxt.getText());
        p.setPreco(Double.parseDouble(precoTxt.getText()));
        p.setTransportadora(transportadoraTxt.getText());
        p.setOrigem(origemTxt.getText());
        p.setCodigo(codigoTxt.getText());
        p.setMaterial(materialTxt.getText());
        p.setProprietario(proprietarioTxt.getText());
        p.setContato(contatoTxt.getText());

        try {
            pdao.cadastrar(p);
            mensagemLbl.setText("<html><strong>Cadastrado com sucesso!</strong></html>");
            nomeTxt.setText("");
            descricaoTxt.setText("");
            precoTxt.setText("");
            transportadoraTxt.setText("");
            origemTxt.setText("");
            codigoTxt.setText("");
            materialTxt.setText("");
            proprietarioTxt.setText("");
            contatoTxt.setText("");
        } catch (ClassNotFoundException | SQLException ex) {
            mensagemLbl.setText("ERRO: " + ex.getMessage());
        }
    }//GEN-LAST:event_cadastrarBtnActionPerformed

    private void deletarFMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarFMIActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Para realizar a exclusão de um cadastro, basta preencher APENAS o campo ID, e clicar no botão \"Deletar\"!", "COMO DELETAR?", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_deletarFMIActionPerformed

    private void consultatodosJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultatodosJMIActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Para realizar a consulta de todos produtos cadastrados, basta clicar no botão \"Consultar todos\"!", "COMO CONSULTAR TODOS?", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_consultatodosJMIActionPerformed

    private void consultarbyidBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarbyidBtnActionPerformed
        // TODO add your handling code here:
        mensagemLbl.setText("...");
        ProdutoDAO pdao = new ProdutoDAO();
        Produto p = new Produto();
        p.setId(Integer.parseInt(idTxt.getText()));

        try {
            boolean idExiste = pdao.verificarExistenciaID(p);
            if (idExiste) {
                p = pdao.consultarById(p);
                nomeTxt.setText(p.getNome());
                descricaoTxt.setText(p.getDescricao());
                precoTxt.setText(Double.toString(p.getPreco()));
                transportadoraTxt.setText(p.getTransportadora());
                origemTxt.setText(p.getOrigem());
                codigoTxt.setText(p.getCodigo());
                materialTxt.setText(p.getMaterial());
                proprietarioTxt.setText(p.getProprietario());
                contatoTxt.setText(p.getContato());

                mensagemLbl.setText("<html><strong>Produto encontrado!</strong><br>"
                        + "<br><strong>ID:</strong> " + p.getId()
                        + "<br><strong>Nome:</strong> " + p.getNome()
                        + "<br><strong>Descrição:</strong> " + p.getDescricao()
                        + "<br><strong>Preço:</strong> " + p.getPreco()
                        + "<br><strong>Transportadora:</strong> " + p.getTransportadora()
                        + "<br><strong>Origem:</strong> " + p.getOrigem()
                        + "<br><strong>Código:</strong> " + p.getCodigo()
                        + "<br><strong>Material:</strong> " + p.getMaterial()
                        + "<br><strong>Proprietário:</strong> " + p.getProprietario()
                        + "<br><strong>Contato:</strong> " + p.getContato()
                        + "</html>");
            } else {
                mensagemLbl.setText("<html><strong>Produto não encontrado</strong>" + "<br><strong>com o ID fornecido. </strong>" + "</html>");
                idTxt.setText("");
                nomeTxt.setText("");
                descricaoTxt.setText("");
                precoTxt.setText("");
                transportadoraTxt.setText("");
                origemTxt.setText("");
                codigoTxt.setText("");
                materialTxt.setText("");
                proprietarioTxt.setText("");
                contatoTxt.setText("");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_consultarbyidBtnActionPerformed

    private void opcaoJMMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcaoJMMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoJMMouseMoved

    private void opcaoJMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcaoJMMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoJMMouseExited

    private void precoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoTxtActionPerformed

    private void consultartodosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultartodosBtnActionPerformed
        // TODO add your handling code here:
        mensagemLbl.setText("...");
        idTxt.setText("");
        ProdutoDAO pdao = new ProdutoDAO();

        try {
            List<Produto> produtos = pdao.consultarTodos();
            if (produtos.isEmpty()) {
                mensagemLbl.setText("<html><strong>Sem nenhum produto cadastrado.</strong></html>");
            } else {

                StringBuilder mensagem = new StringBuilder("<html>");
                for (Produto p : produtos) {
                    mensagem.append("<br><strong>ID:</strong> ").append(p.getId())
                            .append("<br><strong>Nome:</strong> ").append(p.getNome())
                            .append("<br><strong>Descrição:</strong> ").append(p.getDescricao())
                            .append("<br><strong>Preço:</strong> ").append(p.getPreco())
                            .append("<br><strong>Transportadora:</strong> ").append(p.getTransportadora())
                            .append("<br><strong>Origem:</strong> ").append(p.getOrigem())
                            .append("<br><strong>Código:</strong> ").append(p.getCodigo())
                            .append("<br><strong>Material:</strong> ").append(p.getMaterial())
                            .append("<br><strong>Proprietário:</strong> ").append(p.getProprietario())
                            .append("<br><strong>Contato:</strong> ").append(p.getContato())
                            .append("<br>---------------------------")
                            .append("<br>");
                }
                mensagem.append("</html>");

                mensagemLbl.setText(mensagem.toString());
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_consultartodosBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarBtn;
    private javax.swing.JMenuItem atualizarJMI;
    private javax.swing.JPanel botoesPn;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JMenuItem cadastrarJMI;
    private javax.swing.JLabel codigoLbl;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JMenuItem consultabyidJMI;
    private javax.swing.JButton consultarbyidBtn;
    private javax.swing.JButton consultartodosBtn;
    private javax.swing.JMenuItem consultatodosJMI;
    private javax.swing.JLabel contatoLbl;
    private javax.swing.JTextField contatoTxt;
    private javax.swing.JPanel dadosPn;
    private javax.swing.JButton deletarBtn;
    private javax.swing.JMenuItem deletarFMI;
    private javax.swing.JLabel descricaoLbl;
    private javax.swing.JTextField descricaoTxt;
    private javax.swing.JScrollPane espacoPn;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTxt;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel materialLbl;
    private javax.swing.JTextField materialTxt;
    private javax.swing.JLabel mensagemLbl;
    private javax.swing.JLabel nomeLbl;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JMenu opcaoJM;
    private javax.swing.JLabel origemLbl;
    private javax.swing.JTextField origemTxt;
    private javax.swing.JLabel precoLbl;
    private javax.swing.JTextField precoTxt;
    private javax.swing.JLabel proprietarioLbl;
    private javax.swing.JTextField proprietarioTxt;
    private javax.swing.JLabel tituloLbl;
    private javax.swing.JLabel transportadoraLbl;
    private javax.swing.JTextField transportadoraTxt;
    // End of variables declaration//GEN-END:variables
}
